[package]
name = "triangle"
version = "0.1.0"
authors = ["Marek Nagy <62247071@cuni.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
